## Операції над масивами

In [2]:
def homework(message):
    print("\n>>>>>", message, "\n")
import numpy as np

In [3]:
l = (3, 3)

O = np.ones(l)
R = np.random.random(l)
Z = np.zeros(l)
C = np.arange(l[0])
print(R)
print(f"""
Віднімання:\n {C - (O + 10)}
Множення:\n {O * R}
Ділення:\n {R / C}
Степінь:\n {C ** Z}
Поріняння:\n {R > 0.5}
Ділення на 0:\n {O / Z}
""")
homework("""
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
""")
eye_m = np.eye(3) 
print("Матриця eye:\n", eye_m)

c_ones = eye_m == 1
print("\nПорівняння на наявність одиниць:\n", c_ones)

ones_m = np.ones((3, 3))  
print("\nМатриця ones:\n", ones_m)
result = ones_m - eye_m
print("\nРізниця між ones та eye:\n", result)

[[0.09672723 0.49986978 0.67018521]
 [0.82768452 0.6200203  0.07404723]
 [0.7641045  0.42082364 0.14782794]]

Віднімання:
 [[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]
Множення:
 [[0.09672723 0.49986978 0.67018521]
 [0.82768452 0.6200203  0.07404723]
 [0.7641045  0.42082364 0.14782794]]
Ділення:
 [[       inf 0.49986978 0.33509261]
 [       inf 0.6200203  0.03702362]
 [       inf 0.42082364 0.07391397]]
Степінь:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Поріняння:
 [[False False  True]
 [ True  True False]
 [ True False False]]
Ділення на 0:
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


>>>>> 
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
 

Матриця eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Порівняння на наявність одиниць:
 [[ True False False]
 [False  True False]
 [False False  True]]

Матриця ones:
 [[1. 

C:\Users\Mykola\AppData\Local\Temp\ipykernel_18272\3613232203.py:11: RuntimeWarning: divide by zero encountered in divide
  Ділення:\n {R / C}
C:\Users\Mykola\AppData\Local\Temp\ipykernel_18272\3613232203.py:14: RuntimeWarning: divide by zero encountered in divide
  Ділення на 0:\n {O / Z}


## Множення матриць

In [4]:
A = np.array([ [1, 2, 3], [2, 2, 2], [3, 3, 3] ])
B = np.array([ [3, 2, 1], [1, 2, 3], [-1, -2, -3] ])
print(f"Маємо два масиви:\n {A} \n {B}")

R = A * B
print(f"Тут виконується поелементне множення:\n {R}")

R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n {R}")

R = A * B
print(f"Тут масиви перетворені на матриці і далі перемножуються:\n {R}")

Маємо два масиви:
 [[1 2 3]
 [2 2 2]
 [3 3 3]] 
 [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]


## Вирівнювання розмірностей


In [5]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
C = B[:, np.newaxis]

print(f"Вектор В є рядком {B.shape}: {B} тому додавання буде по рядках:\n {A + B}")

print(f"""Вектор C є стовпцем {C.shape}:
{C}
тому додавання буде по стовпцям:
{A + C}""")

print(f"У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:\n {B + C}")

Вектор В є рядком (3,): [1 2 3] тому додавання буде по рядках:
 [[12 14 16]
 [22 24 26]
 [32 34 36]]
Вектор C є стовпцем (3, 1):
[[1]
 [2]
 [3]]
тому додавання буде по стовпцям:
[[12 13 14]
 [23 24 25]
 [34 35 36]]
У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


## Конкатенація, повторення та зміна форми (shape)

In [6]:
D = np.ones(3)
Z = np.zeros((3,1))

print(f"""
При конкатенації рядків маємо: {np.concatenate((D, D))}
При конкатенації стовпців маємо:\n{np.concatenate((Z, Z))}
Масив D {D} має розмірність {D.shape} тому може виконати операцію конкатенації з В {B} розмірністю {B.shape}:
{np.concatenate((B, D))}
Для конкатенації з С
{C}
де С має розмірність = {C.shape} потрібно змінити розмірність D = {D.shape}
Це можна ось так:
{D[:, np.newaxis].shape}
врезультаті ми можем виконати конкатенацію:
{np.concatenate((C, D.reshape((3,1))))}
При повторенні D {D} 2 рази для рядкі та 3 для стовпців будем мати:
{np.tile(D, (2, 3))}
Як бачимо конкатенація та повторення є дещо схожими у деяких випадках:
- конможна перетворити двовимірний масив A розмірністю {A.shape} на рядок: {A.flatten()} з розмірністю {A.flatten().shape}
""")


homework(f"""Створіть двохвимірний масив за допомогою arange та виконайте конкатенацію та повторення.
Створіть масив в якому кількість рядкі та стовпців різна. Спробуйте виконати конкатенацію такого масиву з попереднім. Якщо розмірність масивів не спаівпадє використайте reshape.
Створіть декіль двовимірних масивів з сумарною розмірністю 12 та знайдіть всі можливі комбінції reshape. Наприклад, перша комбінація це рядок - {np.ones((1,12))}
""")


arr1 = np.arange(6).reshape(2, 3)
print("Початковий масив arr1:\n",arr1)

result1=np.concatenate((arr1,arr1))
print("Конкатенований масив:\n",result1)
repeated = np.tile(arr1, (2,2))
print("Повторений масив:\n",repeated)

arr2 = np.arange(12).reshape(4, 3)
print("Початковий масив arr2:\n",arr2)
result2=np.concatenate((arr1, arr2))
print("Конкатенований масив arr1 з arr2:\n",result2)

arr = np.arange(12)

print("\nМожливі reshape комбінації для масиву з розмірністю 12:")

for rows in range(1, 13):
    cols = 12 // rows
    if rows * cols == 12:
        reshaped_arr = arr.reshape((rows, cols))
        print(f"reshape({rows}, {cols}):\n{reshaped_arr}\n")


При конкатенації рядків маємо: [1. 1. 1. 1. 1. 1.]
При конкатенації стовпців маємо:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Масив D [1. 1. 1.] має розмірність (3,) тому може виконати операцію конкатенації з В [1 2 3] розмірністю (3,):
[1. 2. 3. 1. 1. 1.]
Для конкатенації з С
[[1]
 [2]
 [3]]
де С має розмірність = (3, 1) потрібно змінити розмірність D = (3,)
Це можна ось так:
(3, 1)
врезультаті ми можем виконати конкатенацію:
[[1.]
 [2.]
 [3.]
 [1.]
 [1.]
 [1.]]
При повторенні D [1. 1. 1.] 2 рази для рядкі та 3 для стовпців будем мати:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Як бачимо конкатенація та повторення є дещо схожими у деяких випадках:
- конможна перетворити двовимірний масив A розмірністю (3, 3) на рядок: [11 12 13 21 22 23 31 32 33] з розмірністю (9,)


>>>>> Створіть двохвимірний масив за допомогою arange та виконайте конкатенацію та повторення.
Створіть масив в якому кількість рядкі та стовпців різна. Спробуйте виконати конкатенацію такого масиву з попере

## Трансформації масивів

In [7]:
O = np.arange(6).reshape(3,2)
O_r = O.reshape((2,3))
O_f = O.flatten()
O_t = O.transpose()
O_fl = np.flip(O)
O_fa = np.flip(O, axis=1)
'''
print(f"""{O}
Змінити розмірність shape {O.shape} на {O_r.shape} при цьому розмір size {O.size} = {O_r.size} та ndim {np.ndim(O)} = {np.ndim(O_r)}:
{O_r}
Також можна перетворити {np.ndim(O)}-х вимірний масив розмірністю {O.shape} на рядок:
{O_f} 
з розмірністю {O_f.shape} при цьому size = {O_f.size} та ndim стане {np.ndim(O_f)}-х вимірним 
Або транспонувати масив щоб він став {O_t.shape} але зверніть увагу на елементи:
{O_t}
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
{O_fl}
Або обернути лише елементи в кожному рядку (або стовпці):
{O_fa}
""")
'''
homework("""
- Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- Змініть розмірніть перетворивши вектор у матрицю;
- Здійсніть транспонування отриманої матриці та оберніть її;
- Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);
""")
vector = np.arange(12)

shape = vector.shape
size = vector.size
ndim = vector.ndim

print(f"Вектор: {vector}")
print(f"Shape: {shape}")
print(f"Size: {size}")
print(f"Ndim: {ndim}")

matrix = vector.reshape(3, 4)
print(f"\nМатриця {matrix.shape}:\n{matrix}")
m_t=matrix.transpose()
print(f"\nТранспонована матриця:\n{m_t}")
m_fl = np.flip(m_t, axis=1)
print(f"\nОберенена матриця по рядках:\n{m_fl}")
vector_back = m_fl.flatten()
print(f"\nВектор, отриманий з матриці:\n{vector_back}")


>>>>> 
- Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- Змініть розмірніть перетворивши вектор у матрицю;
- Здійсніть транспонування отриманої матриці та оберніть її;
- Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);
 

Вектор: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)
Size: 12
Ndim: 1

Матриця (3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Транспонована матриця:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Оберенена матриця по рядках:
[[ 8  4  0]
 [ 9  5  1]
 [10  6  2]
 [11  7  3]]

Вектор, отриманий з матриці:
[ 8  4  0  9  5  1 10  6  2 11  7  3]
